<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Personal extends Model
{
    public $table = 'personals';

    public $fillable = [
        'n_emp',
        'name',
        'domicilio',
        'telefonos',
        'telefono_contacto',
        'email',
        'fecha_cumple',
        'fecha_inicio_serv',
        'solicitud',
        'check_list_ingreso',
        'carta_compromiso',
        'resguardo',
        'contrato',
        'retencion',
        'renuncia',
        'actas_administrativas',
        'honorarios',
        'identificacion_oficial',
        'acta_nacimiento',
        'curp',
        'curp_doc',
        'rfc',
        'rfc_doc',
        'nss',
        'nss_doc',
        'comprobante_domicilio',
        'comprobante_estudios',
        'recomendaciones',
        'recomendacion_doc',
        'certificado_medico',
        'antecedentes_no_penales',
        'cartilla',
        'enable',
        'otro_doc_nombre',
        'otro_doc',
        // 'epp_pantalon_n',
        // 'epp_pantalon_talla',
        // 'epp_camisola_n',
        // 'epp_camisola_talla',
        // 'epp_gorra_n',
        // 'epp_gorra_talla',
        // 'epp_fornitura_n',
        // 'epp_fornitura_talla',
        // 'epp_gas_n',
        // 'epp_pr24_n',
        // 'epp_credencial_n',
        // 'epp_chamarra_n',
        // 'epp_chamarra_talla',
        // 'epp_chaleco_n',
        // 'epp_chaleco_talla',
        // 'epp_coipa_n',
        // 'epp_guantes_n',
        // 'epp_guantes_talla',
        // 'epp_lampara_n',
        // 'epp_cubrebocas_n',
        // 'epp_tapones_n',
        // 'epp_lentes_n',
        'observaciones',
        'foto',
        'const_sit_fiscal_doc'
    ];

    protected $casts = [
        'n_emp' => 'string',
        'name' => 'string',
        'domicilio' => 'string',
        'telefonos' => 'string',
        'telefono_contacto' => 'string',
        'email' => 'string',
        'fecha_cumple' => 'date',
        'fecha_inicio_serv' => 'date',
        'solicitud' => 'boolean',
        'check_list_ingreso' => 'boolean',
        'carta_compromiso' => 'boolean',
        'resguardo' => 'boolean',
        'contrato' => 'boolean',
        'retencion' => 'boolean',
        'renuncia' => 'boolean',
        'actas_administrativas' => 'boolean',
        'honorarios' => 'boolean',
        'identificacion_oficial' => 'boolean',
        'acta_nacimiento' => 'boolean',
        'curp' => 'string',
        'curp_doc' => 'boolean',
        'rfc' => 'string',
        'rfc_doc' => 'boolean',
        'nss' => 'string',
        'nss_doc' => 'boolean',
        'comprobante_domicilio' => 'boolean',
        'comprobante_estudios' => 'boolean',
        'recomendacion_doc' => 'boolean',
        'certificado_medico' => 'boolean',
        'antecedentes_no_penales' => 'boolean',
        'cartilla' => 'boolean',
        'enable' => 'boolean',
        'otro_doc_nombre' => 'string',
        'otro_doc' => 'boolean',
        // 'epp_pantalon_n' => 'integer',
        // 'epp_pantalon_talla' => 'string',
        // 'epp_camisola_n' => 'integer',
        // 'epp_camisola_talla' => 'string',
        // 'epp_gorra_n' => 'integer',
        // 'epp_gorra_talla' => 'string',
        // 'epp_fornitura_n' => 'integer',
        // 'epp_fornitura_talla' => 'string',
        // 'epp_gas_n' => 'integer',
        // 'epp_pr24_n' => 'integer',
        // 'epp_credencial_n' => 'integer',
        // 'epp_chamarra_n' => 'integer',
        // 'epp_chamarra_talla' => 'string',
        // 'epp_chaleco_n' => 'integer',
        // 'epp_chaleco_talla' => 'string',
        // 'epp_coipa_n' => 'integer',
        // 'epp_guantes_n' => 'integer',
        // 'epp_guantes_talla' => 'string',
        // 'epp_lampara_n' => 'integer',
        // 'epp_cubrebocas_n' => 'integer',
        // 'epp_tapones_n' => 'integer',
        // 'epp_lentes_n' => 'integer',
        'observaciones' => 'string',
        'foto' => 'string',
        'const_sit_fiscal_doc' => 'boolean'
    ];

    public static array $rules = [
        'n_emp' => 'required|string|max:255',
        'name' => 'required|string|max:255',
        'domicilio' => 'string|max:255',
        'telefonos' => 'nullable|string|max:255',
        'telefono_contacto' => 'nullable|string|max:255',
        'email' => 'nullable|string|max:255',
        'fecha_cumple' => 'nullable',
        'fecha_inicio_serv' => 'nullable',
        'solicitud' => 'nullable|boolean',
        'check_list_ingreso' => 'nullable|boolean',
        'carta_compromiso' => 'nullable|boolean',
        'resguardo' => 'nullable|boolean',
        'contrato' => 'nullable|boolean',
        'retencion' => 'nullable|boolean',
        'renuncia' => 'nullable|boolean',
        'actas_administrativas' => 'nullable|boolean',
        'honorarios' => 'nullable|boolean',
        'identificacion_oficial' => 'nullable|boolean',
        'acta_nacimiento' => 'nullable|boolean',
        'curp' => 'nullable|string|max:255',
        'curp_doc' => 'nullable|boolean',
        'rfc' => 'nullable|string|max:255',
        'rfc_doc' => 'nullable|boolean',
        'nss' => 'nullable|string|max:255',
        'nss_doc' => 'nullable|boolean',
        'comprobante_domicilio' => 'nullable|boolean',
        'comprobante_estudios' => 'nullable|boolean',
        'recomendaciones' => 'nullable',
        'recomendacion_doc' => 'nullable|boolean',
        'certificado_medico' => 'nullable|boolean',
        'antecedentes_no_penales' => 'nullable|boolean',
        'cartilla' => 'nullable|boolean',
        // 'created_at' => 'required',
        // 'updated_at' => 'required',
        'enable' => 'boolean',
        'otro_doc_nombre' => 'nullable|string|max:255',
        'otro_doc' => 'nullable|boolean',
        // 'epp_pantalon_n' => 'nullable',
        // 'epp_pantalon_talla' => 'nullable|string|max:255',
        // 'epp_camisola_n' => 'nullable',
        // 'epp_camisola_talla' => 'nullable|string|max:255',
        // 'epp_gorra_n' => 'nullable',
        // 'epp_gorra_talla' => 'nullable|string|max:255',
        // 'epp_fornitura_n' => 'nullable',
        // 'epp_fornitura_talla' => 'nullable|string|max:255',
        // 'epp_gas_n' => 'nullable',
        // 'epp_pr24_n' => 'nullable',
        // 'epp_credencial_n' => 'nullable',
        // 'epp_chamarra_n' => 'nullable',
        // 'epp_chamarra_talla' => 'nullable|string|max:255',
        // 'epp_chaleco_n' => 'nullable',
        // 'epp_chaleco_talla' => 'nullable|string|max:255',
        // 'epp_coipa_n' => 'nullable',
        // 'epp_guantes_n' => 'nullable',
        // 'epp_guantes_talla' => 'nullable|string|max:255',
        // 'epp_lampara_n' => 'nullable',
        // 'epp_cubrebocas_n' => 'nullable',
        // 'epp_tapones_n' => 'nullable',
        // 'epp_lentes_n' => 'nullable'
        'foto' => 'nullable',
        'const_sit_fiscal_doc' => 'nullable|boolean',
    ];

    public function asistencias(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(\App\Models\Asistencia::class, 'idPersonal');
    }
}
