<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Personal extends Model
{
    public $table = 'personals';

    public $fillable = [
        'n_emp',
        'name',
        'domicilio',
        'telefonos',
        'telefono_contacto',
        'email',
        'fecha_cumple',
        'fecha_inicio_serv',
        'solicitud',
        'check_list_ingreso',
        'carta_compromiso',
        'resguardo',
        'contrato',
        'retencion',
        'renuncia',
        'actas_administrativas',
        'honorarios',
        'identificacion_oficial',
        'acta_nacimiento',
        'curp',
        'curp_doc',
        'rfc',
        'rfc_doc',
        'nss',
        'nss_doc',
        'comprobante_domicilio',
        'comprobante_estudios',
        'recomendaciones',
        'recomendación_doc',
        'certificado_medico',
        'antecedentes_no_penales',
        'cartilla',
        'enable',
        'otro_doc_nombre',
        'otro_doc',
        'epp_pantalon_n',
        'epp_pantalon_talla',
        'epp_camisola_n',
        'epp_camisola_talla',
        'epp_gorra_n',
        'epp_gorra_talla',
        'epp_fornitura_n',
        'epp_fornitura_talla',
        'epp_gas_n',
        'epp_pr24_n',
        'epp_credencial_n',
        'epp_chamarra_n',
        'epp_chamarra_talla',
        'epp_chaleco_n',
        'epp_chaleco_talla',
        'epp_coipa_n',
        'epp_guantes_n',
        'epp_guantes_talla',
        'epp_lampara_n',
        'epp_cubrebocas_n',
        'epp_tapones_n',
        'epp_lentes_n'
    ];

    protected $casts = [
        'n_emp' => 'string',
        'name' => 'string',
        'domicilio' => 'string',
        'telefonos' => 'string',
        'telefono_contacto' => 'string',
        'email' => 'string',
        'fecha_cumple' => 'date',
        'fecha_inicio_serv' => 'date',
        'solicitud' => 'boolean',
        'check_list_ingreso' => 'boolean',
        'carta_compromiso' => 'boolean',
        'resguardo' => 'boolean',
        'contrato' => 'boolean',
        'retencion' => 'boolean',
        'renuncia' => 'boolean',
        'actas_administrativas' => 'boolean',
        'honorarios' => 'boolean',
        'identificacion_oficial' => 'boolean',
        'acta_nacimiento' => 'boolean',
        'curp' => 'string',
        'curp_doc' => 'boolean',
        'rfc' => 'string',
        'rfc_doc' => 'boolean',
        'nss' => 'string',
        'nss_doc' => 'boolean',
        'comprobante_domicilio' => 'boolean',
        'comprobante_estudios' => 'boolean',
        'recomendaciones' => 'integer',
        'recomendación_doc' => 'boolean',
        'certificado_medico' => 'boolean',
        'antecedentes_no_penales' => 'boolean',
        'cartilla' => 'boolean',
        'enable' => 'boolean',
        'otro_doc_nombre' => 'string',
        'otro_doc' => 'bolean',
        'epp_pantalon_n' => 'integer',
        'epp_pantalon_talla' => 'string',
        'epp_camisola_n' => 'integer',
        'epp_camisola_talla' => 'string',
        'epp_gorra_n' => 'integer',
        'epp_gorra_talla' => 'string',
        'epp_fornitura_n' => 'integer',
        'epp_fornitura_talla' => 'string',
        'epp_gas_n' => 'integer',
        'epp_pr24_n' => 'integer',
        'epp_credencial_n' => 'integer',
        'epp_chamarra_n' => 'integer',
        'epp_chamarra_talla' => 'string',
        'epp_chaleco_n' => 'integer',
        'epp_chaleco_talla' => 'string',
        'epp_coipa_n' => 'integer',
        'epp_guantes_n' => 'integer',
        'epp_guantes_talla' => 'string',
        'epp_lampara_n' => 'integer',
        'epp_cubrebocas_n' => 'integer',
        'epp_tapones_n' => 'integer',
        'epp_lentes_n' => 'integer'
    ];

    public static array $rules = [
        'n_emp' => 'required|string|max:255',
        'name' => 'required|string|max:255',
        'domicilio' => 'required|string|max:255',
        'telefonos' => 'required|string|max:255',
        'telefono_contacto' => 'required|string|max:255',
        'email' => 'required|string|max:255',
        'fecha_cumple' => 'nullable',
        'fecha_inicio_serv' => 'nullable',
        'solicitud' => 'boolean',
        'check_list_ingreso' => 'boolean',
        'carta_compromiso' => 'boolean',
        'resguardo' => 'boolean',
        'contrato' => 'boolean',
        'retencion' => 'boolean',
        'renuncia' => 'boolean',
        'actas_administrativas' => 'boolean',
        'honorarios' => 'boolean',
        'identificacion_oficial' => 'boolean',
        'acta_nacimiento' => 'boolean',
        'curp' => 'string|max:255',
        'curp_doc' => 'boolean',
        'rfc' => 'string|max:255',
        'rfc_doc' => 'required|boolean',
        'nss' => 'string|max:255',
        'nss_doc' => 'required|boolean',
        'comprobante_domicilio' => 'required|boolean',
        'comprobante_estudios' => 'required|boolean',
        'recomendaciones' => 'required|numeric',
        'recomendacion_doc' => 'boolean',
        'certificado_medico' => 'boolean',
        'antecedentes_no_penales' => 'required|boolean',
        'cartilla' => 'boolean',
        // 'created_at' => 'required',
        // 'updated_at' => 'required',
        'enable' => 'boolean',
        'otro_doc_nombre' => 'string',
        'otro_doc' => 'bolean',
        'epp_pantalon_n' => 'numeric',
        'epp_pantalon_talla' => 'string',
        'epp_camisola_n' => 'numeric',
        'epp_camisola_talla' => 'string',
        'epp_gorra_n' => 'numeric',
        'epp_gorra_talla' => 'string',
        'epp_fornitura_n' => 'numeric',
        'epp_fornitura_talla' => 'string',
        'epp_gas_n' => 'numeric',
        'epp_pr24_n' => 'numeric',
        'epp_credencial_n' => 'numeric',
        'epp_chamarra_n' => 'numeric',
        'epp_chamarra_talla' => 'string',
        'epp_chaleco_n' => 'numeric',
        'epp_chaleco_talla' => 'string',
        'epp_coipa_n' => 'numeric',
        'epp_guantes_n' => 'numeric',
        'epp_guantes_talla' => 'string',
        'epp_lampara_n' => 'numeric',
        'epp_cubrebocas_n' => 'numeric',
        'epp_tapones_n' => 'numeric',
        'epp_lentes_n' => 'numeric'
    ];

}
